version: '3'

services:
    nginx:
        container_name: nginx01
        image: nginx:1.19.8
        restart: always
        ports:
           - 8080:80
        volumes:
           - ../cwd:/var/www/cwd
           - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf  
           - ./access.log:/var/log/nginx/access.log
           - ./error.log:/var/log/nginx/error.log
           - ./status.sh:/var/log/nginx/status.sh
        #command: >
          #sh -c "curl http://localhost:8080"
